---
meta:
  name:    redis-forge
  release: Blacksmith Redis Forge
  target:  pipes/blacksmith
  url:     https://pipes.scalecf.net
  iaas:            vsphere
  exposed:         no
  version_file:    version
  initial_version: 2.1.0

  manifest:
    path: ci/manifest.yml

  git:
    name:  ((cloudfoundry-community-ci-bot-github.name))
    email: ((cloudfoundry-community-ci-bot-github.email))

  bosh-lite:
    target:   ((thunder-dome.url))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cloudfoundry-community-aws.access_key_id))
    secret_key: ((cloudfoundry-community-aws.secret_access_key))

  github:
    owner:  blacksmith-community
    repo:   redis-forge-boshrelease
    branch: master
    private_key:  ((cloudfoundry-community-ci-bot-github.private_key))
    access_token: ((cloudfoundry-community-ci-bot-github.access_token))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
